apiVersion: v1
kind: Secret
metadata:
  name: database-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  DB_USERNAME: cm9vdA==  # root
  DB_PASSWORD: cGFzc3dvcmQ=  # password
---
apiVersion: v1
kind: Secret
metadata:
  name: jwt-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with actual encoded secrets
  JWT_SECRET: eW91ci1zdXBlci1zZWNyZXQtand0LWtleQ==  # your-super-secret-jwt-key
  JWT_REFRESH_SECRET: eW91ci1yZWZyZXNoLXNlY3JldA==  # your-refresh-secret
---
apiVersion: v1
kind: Secret
metadata:
  name: aws-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with actual AWS credentials
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: stripe-secrets
  namespace: ecommerce
type: Opaque
data:
  # Base64 encoded values - replace with actual Stripe keys
  STRIPE_SECRET_KEY: ""
  STRIPE_WEBHOOK_SECRET: ""
